### ISSUE TITLE
[Bug]: When using "Peek at desktop" the video stays paused

### ISSUE THREAD

**Issue by Kingproone** [luisbocanegra/plasma-smart-video-wallpaper-reborn#101]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version: 2.1.0

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**
I use plasmas screen edges feature and have the peek at desktop enabled on one corner, when hovering it from a maxximised app and get the desktop shown, the video playback stays paused.

I don't fully know whether this is a limitation with how the whole plugin is implemented or just a bug.

**Steps to reproduce**

1. Go to 'Settings -> mouse & touchpad -> screen edges'
2. Click on one of the 8 available options and set it to peek at desktop
3. click apply and hover over that area

**Observed Result**
The video playback is paused

**Expected Result**
The video starts playing

**System information (kinfo):**
```yaml
Operating System: EndeavourOS
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD FX(tm)-6100 Six-Core Processor
Memory: 7.7 GiB of RAM
Graphics Processor: AMD Radeon RX 460 Graphics
```
