### ISSUE TITLE
[Bug]: It is not compatible with mesa-git

### ISSUE THREAD

**Issue by laichiaheng** [luisbocanegra/plasma-smart-video-wallpaper-reborn#104]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**

![Image](https://github.com/user-attachments/assets/1bcef54a-6af2-4a57-ba4c-e124fcf928ec)

**Steps to reproduce**

1. Install mesa-git

**Observed Result**
Many green lines.

**Expected Result**
Normal

**Screenshots/Video**
![Image](https://github.com/user-attachments/assets/1bcef54a-6af2-4a57-ba4c-e124fcf928ec)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
# Operating System: Arch Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

**Additional context**
