### ISSUE TITLE
[Bug]: Audio stops working

### ISSUE THREAD

**Issue by NickTheOnlyNeko** [luisbocanegra/plasma-smart-video-wallpaper-reborn#110]
I have:

- [x] I've searched if this issue hasn't been reported yet.
- [x] I've verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [x] AUR
- [ ] Manually from the latest source code

**Describe the bug**

**Steps to reproduce**

1: set up a video that has sound
2: focus on a window or something like it so it will freeze the video and the music
3: wait for like 30 minutes
4: go back to your wallpaper and Tada no sound

**Observed Result**
Please describe and attach terminal error output (if any)
1: I don't know how

**Expected Result**
1: for the music to be in sync with the video and to not be breaking resulting into it only having video and no audio.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.12.0
Qt Version: 6.9.0
Kernel Version: 6.12.22-1-lts (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD Ryzen 5 3500X 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 5500 XT
```

- Things in your system that might be relevant: [e.g. Kwin scripts(got none(basically Vanilla)), Themes(Vanilla), Addons(the Plasma Smart Video Wallpaper, other than that nope)]

**Additional context**

![Image](https://github.com/user-attachments/assets/540d0e7f-fd5e-4e90-8f78-5f0de5cea3cb)
