### ISSUE TITLE
[Bug]: No option to add videos when setting up

### ISSUE THREAD

**Issue by thebrandonlucas** [luisbocanegra/plasma-smart-video-wallpaper-reborn#119]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**

I followed the instructions in [Usage -> As Desktop Wallpaper](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn?tab=readme-ov-file#as-desktop-wallpaper), but there is no option to add videos, as seen in the screenshot below. When clicking apply, I only get a black wallpaper and don't see anywhere to add videos.

I apologize that I'm unsure of how to check the version, but I installed directly from the KDE "Download New Wallpaper Plugins" option.

Thank you for your help.

![Image](https://github.com/user-attachments/assets/ca60d205-d915-43a6-9f1b-e90b76a6efe0)

**Steps to reproduce**

1. Right click on the Desktop > Desktop and Wallpaper
2. Change Wallpaper type to "Smart Video Wallpaper Reborn"

See no options available

Run `kinfo` on a terminal and paste the output bellow

```yaml
# paste output of kinfo here
Operating System: NixOS 24.11
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.2
Kernel Version: 6.6.87 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7640U w/ Radeon 760M Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon 760M
```
