### ISSUE TITLE
[Bug]: Video playing is broken with mesa25.1

### ISSUE THREAD

**Issue by laichiaheng** [luisbocanegra/plasma-smart-video-wallpaper-reborn#126]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**
Many green and red lines across the wallpaper.

**Steps to reproduce**

1. Upgrade to mesa25.1
2. reboot

**Observed Result**
Video playback is broken

**Expected Result**
Works as usual.

**Screenshots/Video**
[Video Link](https://youtu.be/Bf6s6drA78I)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.3.5
KDE Frameworks Version: 6.14.0
Qt Version: 6.9.0
Kernel Version: 6.14.7-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT

```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

**Additional context**
