### ISSUE TITLE
[Bug]: Weird artifacts in the video not present in MPV

### ISSUE THREAD

**Issue by JurgenCruz** [luisbocanegra/plasma-smart-video-wallpaper-reborn#141]
I have:

- [X] Searched if this issue hasn't been reported yet.
- [X] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [X] AUR
- [ ] Manually from the latest source code

**Describe the bug**
I have a video that I made myself by converting a series of pngs to mp4. This video looks perfectly fine in both VLC and MPV with hardware acceleration. However when I use it as background with this plugin, the colors go to black and white and blue and green horizontal lines appear.

The command I used to generate the video is

`ffmpeg -i '%04d.png' -framerate 29.97 -c:v libx264 -pix_fmt yuv420p 'output.mp4'`

if I however remove the yuv420, it generates a 444 format which works correctly but it can no longer use hardware acceleration.

**Steps to reproduce**

1. Set the video as the only video in the playlist
2. Click on Apply

**Observed Result**
The video is rendered with weird artifacts

**Expected Result**
video is played correctly as in VLC or MPV

**Screenshots/Video**
Background:
![Image](https://github.com/user-attachments/assets/93011bb8-1b69-416f-84df-b815116dcec0)

VLC:
![Image](https://github.com/user-attachments/assets/2f3a5bb6-62b0-45f2-a65f-f5875c4e9da1)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: EndeavourOS
KDE Plasma Version: 6.4.0
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.3-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 7900X 12-Core Processor
Memory: 64 GiB of RAM (61.9 GiB usable)
Graphics Processor 1: AMD Radeon RX 6950 XT
Graphics Processor 2: AMD Radeon Graphics
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]
I was originally using qt6-multimedia-ffmpeg, but at some point in my testing it stopped working and I only got black screens. I installed the gstreamer version and it started working again, but still with artifacts.

**Additional context**
any other video I tried which is also yuv420 works fine, and this video created in yuv 444 it also works fine, but for some reason this video doesn't work in yuv420. I don't know what other settings in ffmpeg I can use to encode it such that it works and also can use HW Accel.
