### ISSUE TITLE
[Bug]: Translations don't appear

### ISSUE THREAD

**Issue by ArthurLobopro** [luisbocanegra/plasma-smart-video-wallpaper-reborn#84]
I have:

- [ x ] Searched if this issue hasn't been reported yet.
- [ x ] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [ x ] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**
The version 2.0.0 should have some pt_BR translations but these translations are not being applied

**Steps to reproduce**

1. Use pt_BR as system language
2. Open the plugin config

**Observed Result**
The translations are not there

**Expected Result**
The texts should be in pt_BR

**Screenshots/Video**

![Image](https://github.com/user-attachments/assets/8c9fb215-0292-4a13-a322-a7f3be205527)
The translation is not applied 

**System information:**

```yaml
Operating System: BigLinux based in Manjaro Linux 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.2
Kernel Version: 6.6.75-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-3570 CPU @ 3.40GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
```

- Things in your system that might be relevant: My Language ENV

LANGUAGE=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_MONETARY=pt_BR.UTF-8
LC_PAPER=pt_BR.UTF-8
LANG=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
