### ISSUE TITLE
[Bug]: Blank video on Nvidia hardware on Wayland with both ffmpeg and Gstreamer backends

### ISSUE THREAD

**Issue by LogistyxCat** [luisbocanegra/plasma-smart-video-wallpaper-reborn#96]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**
When changing the wallpaper through the KDE Desktop Folder Settings, the background changes instead to a completely black screen, without crashes to date. There is no apparent increase in VRAM usage after changing back.

This happened before and after setting `QT_MEDIA_BACKEND=gstreamer`.

**Steps to reproduce**

1. Go to 'Desktop and Folder Settings'
2. Click on the 'Wallpaper type' dropdown
3. Select the 'Smart Video Wallpaper Reborn' option
4. Click 'Add new videos'
5. Ensure that at least one video of any file type has been selected
6. Click 'Apply'

**Observed Result**
A completely black wallpaper on the configured screen with no noticeable increase in VRAM usage.

**Expected Result**
The video plays as a wallpaper.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

![Image](https://github.com/user-attachments/assets/ac5d8c1e-193b-42d7-869c-061acd2c7193)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output below

```yaml
kinfo                                                                            
Operating System: Manjaro Linux 
KDE Plasma Version: 6.3.2
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.14.0-rc5-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7600 6-Core Processor
Memory: 30.3 GiB of RAM
Graphics Processor 1: NVIDIA GeForce RTX 4070/PCIe/SSE2
Graphics Processor 2: NVIDIA GeForce RTX 4070/PCIe/SSE2
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

```yaml
inxi -G                                                                                                           ✔ 
Graphics:
  Device-1: NVIDIA AD104 [GeForce RTX 4070] driver: nvidia v: 570.124.04
  Device-2: Advanced Micro Devices [AMD/ATI] Raphael driver: amdgpu
    v: kernel
  Display: wayland server: X.org v: 1.21.1.16 with: Xwayland v: 24.1.6
    compositor: kwin_wayland driver: X: loaded: nvidia
    gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1440~75Hz
    2: 2560x1440~75Hz
  API: EGL v: 1.5 drivers: nvidia platforms: wayland,x11,surfaceless
  API: OpenGL v: 4.6.0 vendor: nvidia v: 570.124.04 renderer: NVIDIA
    GeForce RTX 4070/PCIe/SSE2
  API: Vulkan v: 1.4.304 drivers: N/A surfaces: xcb,xlib,wayland
  Info: Tools: api: clinfo, eglinfo, glxinfo, vulkaninfo
    de: kscreen-console,kscreen-doctor gpu: nvidia-settings,nvidia-smi
    wl: wayland-info x11: xdpyinfo, xprop, xrandr
```

**Additional context**
Videos play without issue in mpv, vlc, etc.
